### ISSUE TITLE
Users who qualify for free permits need to be shown and asked relevant information

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#537] opened 2017-05-26 10:22 UTC
Hi @sanjaypoyzer the user journey where a user does not need to pay for a permit needs fixing. We need to demonstrate (as my basic diagram illustrates) that when a user qualifies for a free permit, he should be shown a suitable summary page (see #339) and not shown any payment pages. 

![flow](https://cloud.githubusercontent.com/assets/20285115/26490974/7d239f30-4205-11e7-9cf1-7b67c4c51c4b.jpg)

this picture shows a flow for when a user is eligible for a free permit when he either lives in a HMO, is a blue badge holder or is applying for the 1st permit of a household which is free

**Comment by EUzkuraityte** [comment] 2017-06-12 14:31
Evidence from sunderland
![image](https://user-images.githubusercontent.com/20285115/27038881-2d26543c-4f84-11e7-94af-2c398dbe53a2.png)

**Comment by suryanaga** [comment] 2017-06-13 12:38
This is a duplicate of #399

**Closed as completed by suryanaga** 2017-06-13 12:38 UTC
Labels: payment, Parking Permits, Cost of permit

**Comment by EUzkuraityte** [comment] 2017-06-13 13:21
no probs, I copied all the info from this comment into #565
