### ISSUE TITLE
Users unsure where their permit allowed them to park

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#328] opened 2017-04-11 14:06 UTC
![issue7](https://cloud.githubusercontent.com/assets/27288208/24913240/71c3a690-1ec8-11e7-87bb-c7bea1d9e8e5.PNG)

**Comment by EUzkuraityte** [comment] 2017-04-11 15:33
This is a duplicate of #239

**Closed as completed by EUzkuraityte** 2017-04-11 15:33 UTC
Labels: Parking Permits
