### ISSUE TITLE
users didnt realise they were finished

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#352] opened 2017-04-13 07:41 UTC

**Comment by suryanaga** [comment] 2017-04-18 12:16
I think this could be an issue with the current styles on Northumberland's prototype.

**Comment by petegale** [comment] 2017-04-18 12:47
@sanjaypoyzer It's worth noting that this issue has also been reported by Bucks and Sunderland as well as in round 1 of parking permits for Argleton. So it may not just be styling.

**Comment by suryanaga** [comment] 2017-04-18 13:46
@petegale Ok, I'm going to do some organising of all the issues related to this page because there's a few now...

**Comment by suryanaga** [comment] 2017-04-18 14:29
OK, so #237 is the related issue for Parking Permits. As per other issues, we'll keep both around. That issue now also references #327 and #385, although both of those issues have local issues that could do with being addressed.

@petegale Are there any other versions of this issue that I've missed? Have the Bucks issues made it onto github yet?

**Comment by petegale** [comment] 2017-04-18 14:38
@sanjaypoyzer not that I'm aware of. @samuelculley should be doing the Bucks issues today or tomorrow

**Comment by irinapencheva** [comment] 2017-04-21 10:29
@sanjaypoyzer - this is also an issue for Bucks #425

**Comment by suryanaga** [comment] 2017-05-11 16:17
Duplicate of #237

**Closed as completed by suryanaga** 2017-05-11 16:17 UTC
Labels: Northumberland, success-page, Concessionary Travel, local issue
