### ISSUE TITLE
costs are incorrect

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#357] opened 2017-04-13 07:46 UTC

**Comment by EUzkuraityte** [comment] 2017-04-21 15:39
Hi @joanneSouthern is this a local issue or the common prototype?

Hi @sanjaypoyzer I assume that LAs should be able to display the permit price set by their council in their prototype. Is that correct?

**Comment by lizziebruce** [comment] 2017-05-11 09:22
See #313

**Comment by lizziebruce** [comment] 2017-05-11 10:29
Believe this is a duplicate of 313 and should be closed – @sanjaypoyzer do you agree?

**Comment by suryanaga** [comment] 2017-05-11 16:25
@EUzkuraityte Yes councils can set the costs by submitting a pull request.

**Closed as completed** 2017-05-11 16:24 UTC
Labels: Northumberland, Parking Permits, needs clarification / more info
