### ISSUE TITLE
Apply for a permit: The cost of the permit is not clear

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#429] opened 2017-04-24 09:10 UTC
Impact: Users may leave the application to try to find more information about the cost of permits.

Evidence: “Don’t see how long it lasts, so not clear on cost.”
I’d want to know the cost so that I could be sure I can cover the cost.”

**Comment by lizziebruce** [comment] 2017-05-11 09:27
See #313

**Comment by suryanaga** [comment] 2017-05-11 16:29
Duplicate of #313.

**Closed as completed by suryanaga** 2017-05-11 16:29 UTC
Labels: Parking Permits, Oxfordshire, Cost of permit
