### ISSUE TITLE
Users need to know what different types of permit they could apply for

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#329] opened 2017-04-11 14:09 UTC
![issue8](https://cloud.githubusercontent.com/assets/27288208/24913344/ce4649f4-1ec8-11e7-8b0b-342129837b2d.PNG)

**Comment by suryanaga** [comment] 2017-05-04 16:25
Duplicate of #294

**Closed as completed by suryanaga** 2017-05-04 16:25 UTC
Labels: content-fix, Parking Permits
