### ISSUE TITLE
Users need a better way to enter dates

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#376] opened 2017-04-13 08:55 UTC
Users felt the layout of this page was poor with boxes too close together.   Users felt a calendar popup to choose a date would be helpful

**Comment by EUzkuraityte** [comment] 2017-05-11 16:55
@sanjaypoyzer please could you advise the reasoning behind boxes vs calendar and in our current date entry display and if the box sizes meet accessibility requirements.

**Comment by EUzkuraityte** [comment] 2017-05-26 11:48
Closing as this is a duplicate of #409

**Closed as completed by EUzkuraityte** 2017-05-26 11:48 UTC
Labels: Northumberland, Parking Permits
