### ISSUE TITLE
Apply for a permit: Users don't read the information under the apply button

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#430] opened 2017-04-24 09:11 UTC
Impact: Users may miss the information telling them what they will need in order to make the application.
Evidence: “Wouldn’t read the rest, I already know what I want. Might just scan it.”
“Unlikely to read the rest of is, would probably just click to apply.”
Users said later in the application that they wish they’d been told what they would need in advance of starting the application.
“No warning of needing documents before this point.”

**Comment by EUzkuraityte** [comment] 2017-05-11 15:03
duplicate of #360

**Closed as completed by EUzkuraityte** 2017-05-11 15:03 UTC
Labels: Parking Permits, Oxfordshire
