### ISSUE TITLE
Verifying your identity page question

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#307] opened 2017-04-11 12:35 UTC
Currently the question is: "How do you want to claim your older person's bus pass?"

Is this the right question? Shouldn't it be 'How do you want to prove your eligibility and identity to claim your ...?"

**Comment by suryanaga** [comment] 2017-04-12 13:27
@irinapencheva Not sure what the issue is here

**Comment by irinapencheva** [comment] 2017-04-12 13:38
@sanjaypoyzer - sorry, wrongly worded comment when I was copy-pasting from my spreadsheet. Reworded the comment above, so hopefully makes more sense now.

**Comment by suryanaga** [comment] 2017-04-12 14:16
So is this a question for research? If so, it should be more along the lines of "Does the user understand x?"

If it's an issue, what is the underlying issue? What's the evidence?

**Comment by irinapencheva** [comment] 2017-04-12 14:31
Let's leave it for the content designer. I think the way the question is worded now is a bit dubious for the task.

**Comment by irinapencheva** [comment] 2017-04-21 09:12
@lizziebruce - would be great if you can take a look when you're working again on the ConTravel pattern 

Happy to discuss as well to clarify what I mean.

**Comment by suryanaga** [comment] 2017-04-21 09:15
@irinapencheva This issue still needs evidence that it's a problem.

**Comment by irinapencheva** [comment] 2017-04-21 09:22
@sanjaypoyzer - I don't think the question is factually fully accurate because it's about verifying your identity, but I'm happy to close/ icebox this issue as it will be covered by another one coming from UR for the "Verifying your identity" page

**Comment by suryanaga** [comment] 2017-04-21 11:57
@irinapencheva Not sure how it's factually inaccurate - The user is choosing how they claim their thing.

**Comment by irinapencheva** [comment] 2017-04-21 12:07
@sanjaypoyzer - means that most people don't understand what the purpose of Verify in the whole transaction is

As said before, happy to close this issue if this will be covered by a wider issue, but as it stands now, this question doesn't help to understand why people go through Verify

**Comment by lizziebruce** [comment] 2017-04-21 12:25
@irinapencheva @sanjaypoyzer 
Several things on this page need revisiting. It needs to be decided whether this step is about verifying ID or seeing if the person is eligible. 

It would seem that it is about verifying ID, as the user should have "self-checked" on the previous page – which gives links to 'check your state pension age' and 'find your local council'. If we have doubt that the user is proficiently self-checking, we should add a step to the journey i.e. Check you are eligible, prior to verify your ID. If they are not eligible there is no user need for them to go through the Verify process here.

So, taking it that this page is purely about verifying ID, here is a copy rewrite. 
NB I have changed the page title to Checking your identity as that is a more plain English term. It also reserves the word 'verify' for the actual GOV.UK Verify brand:

![ct verifying your identity council page](https://cloud.githubusercontent.com/assets/27814324/25276351/a0b47e04-2691-11e7-9331-41243ceb9b78.png)

Added to this, from the UR I observed I'd recommend we change the first radio button text to:

'GOV.UK Verify
Your pass will arrive within 5 working days
You'll need to answer identity questions and upload a photo the first time you use GOV.UK Verify'

Evidence: users were unsure they could sign in without having registered/used Verify before, and also confused signing in with their My Council account. Secondly, the need to upload a photo caused issues for users so worth informing them upfront. Also adding 'if this is the first time' may reduce frustration, as they'll realise it's a one-time thing. Believe these points will be covered in the issues @petegale is adding post-UR analysis. But here's how it could look:

![verify or scan options radio buttons council page](https://cloud.githubusercontent.com/assets/27814324/25276951/8cc6348e-2694-11e7-887e-85b2af72934e.png)

This is how the whole page would look with all the content revisions incorporated:

![ct verifying your id plus new options radio buttons council page](https://cloud.githubusercontent.com/assets/27814324/25277004/cf73c3a0-2694-11e7-8d7b-e87668373d8b.png)

Lastly – perhaps replacing 'identity questions' with 'security questions' could be helpful for users as they would be familiar with the concept of security questions from banking/other services, even if offline users. It also conveys 'keeping your things secure' rather than 'giving out your personal data'.

**Comment by suryanaga** [comment] 2017-04-25 10:17
Closing this issue as covered in #395.

**Comment by irinapencheva** [comment] 2017-04-25 10:20
@sanjaypoyzer - I thought we have to close the issue that's latest if they're related. In this case issue #395 would be that.

Can you confirm what's the process and why we're not following it here?

**Comment by suryanaga** [comment] 2017-04-25 10:43
#395 is a pull request, not an issue (and it is merged)

**Closed as completed by suryanaga** 2017-04-25 10:43 UTC
Labels: content-fix, prove-identity-page, Concessionary Travel, needs clarification / more info
