### ISSUE TITLE
Users aren't realising that they've reached the final page

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#636] opened 2017-07-26 12:03 UTC
Users not realising they had reached the final page. Northumberland suggests adding “Thank you” to the copy. @Pete feels the prior page order may be affecting this. Need to think of solution and test in Beta.

**Comment by pete** [comment] 2017-07-26 16:27
I fear I may have been misunderstood, so I would like to clarify:  although I appreciate that my opinion merits consideration, I have no opinion on whether prior page order is affecting this.

**Comment by lizziebruce** [comment] 2017-10-09 14:34
Closing as duplicate of #425

**Closed as completed by lizziebruce** 2017-10-09 14:34 UTC
Labels: success-page, Concessionary Travel
