### ISSUE TITLE
Users need to know where their permit would allow them to park

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#239] opened 2017-03-13 11:37 UTC
**Impact:** Users will need to carry out further research to understand where their permit is valid for.

**Evidence:** Several users expressed this information need at the end of the transaction.

**Comment by petegale** [comment] 2017-03-13 11:37
![screen shot 2017-03-13 at 11 27 38](https://cloud.githubusercontent.com/assets/2970019/23852796/6df9c48e-07e1-11e7-9263-e95aecddad22.png)

**Comment by EUzkuraityte** [comment] 2017-04-11 15:35
![image](https://cloud.githubusercontent.com/assets/20285115/24917367/d7efe706-1ed4-11e7-9dde-bcc90557424b.png)

**Comment by EUzkuraityte** [comment] 2017-05-03 11:47
![screen shot 2017-05-03 at 12 47 35](https://cloud.githubusercontent.com/assets/20285115/25659231/b623f528-2ffe-11e7-8823-9ff03d42a617.png)

**Comment by ingasiler** [comment] 2017-05-05 12:37
![image](https://cloud.githubusercontent.com/assets/19390851/25745660/f5253aa8-3197-11e7-82f6-dbfd9a357e95.png)

**Comment by ingasiler** [comment] 2017-05-05 14:26
![image](https://cloud.githubusercontent.com/assets/19390851/25749661/36cd3726-31a7-11e7-8018-a943572caa10.png)

**Comment by suryanaga** [comment] 2017-05-08 10:33
We think that when #226 is closed, this one should be solved, so will close this issue as a duplicate and reopen if it's seen again.

**Closed as completed by suryanaga** 2017-05-08 10:33 UTC
Labels: content-fix, success-page, Parking Permits

**Comment by lizziebruce** [comment] 2017-05-10 15:47
@sanjaypoyzer hi, why is this still appearing in ready to do if it's closed? Can I move it to ice box?

**Comment by lizziebruce** [comment] 2017-05-11 09:51
Duplicate of #262? Also covered by #313 updates.
