### ISSUE TITLE
User didn’t know national insurance number or wouldn’t have their nation insurance numbers to hand

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#564] opened 2017-06-12 13:41 UTC
![issue 6](https://user-images.githubusercontent.com/27288208/27036596-35104f10-4f7d-11e7-8be9-a4c4b4420e2c.PNG)

**Comment by EUzkuraityte** [comment] 2017-06-12 14:33
It's a bug in the prototype. Closing this as duplicate of #544

**Closed as completed by EUzkuraityte** 2017-06-12 14:33 UTC
