### ISSUE TITLE
Privacy requirements – full details

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#453] opened 2017-04-24 16:50 UTC
Orvokki Lohikoski advised @sanjaypoyzer and @lizziebruce on 24/04 that there's a need to flag how personal data is stored. Key information that the user may be concerned about should be contextualised in the on-page copy. Full details of all data storage should be accessible throughout the user journey, but it is ok to do this in a tradional way for example a footer link.

**Comment by EUzkuraityte** [comment] 2017-04-25 09:15
I think it's a duplicate of #41 so closing this one and copying this comment to the original issue

**Closed as completed by EUzkuraityte** 2017-04-25 09:15 UTC
Labels: needs clarification / more info
