### ISSUE TITLE
Enter card details: Billing address - users are frustrated by having to repeatedly enter information

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#448] opened 2017-04-24 09:30 UTC
Impact: Users might make mistakes as they become increasingly frustrated.
Evidence: “You know my address already, why do I have to enter a separate billing address?”
“You know my email address already.”
“Annoying I have to enter my address / email again.”
“Now it wants my account again!”

**Comment by EUzkuraityte** [comment] 2017-05-09 13:24
duplicate of #148

**Closed as completed by EUzkuraityte** 2017-05-09 13:24 UTC
Labels: payment, Parking Permits, Oxfordshire
