### ISSUE TITLE
Users not advised when the permit is free of charge.

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#324] opened 2017-04-11 14:00 UTC
![issue3](https://cloud.githubusercontent.com/assets/27288208/24912959/904ad666-1ec7-11e7-907e-99e6fdc1192f.PNG)

**Comment by EUzkuraityte** [comment] 2017-04-11 15:27
This is a duplicate of #297

**Closed as completed by EUzkuraityte** 2017-04-11 15:27 UTC
Labels: Parking Permits
