### ISSUE TITLE
PP: add to section Enter vehicle details

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#105] opened 2017-01-26 14:42 UTC
Hi,

Suggestion from Bucks CC - Integration with the DVLA would be useful here.

I'm inclined to agree on this, but not sure if we want to add this to the service pattern given that V5C data is self asserted and it does not cover cases such as shared cars... 

Please advise what you think.

**Comment by kaydale** [comment] 2017-01-31 13:49
@EUzkuraityte what needs to change to the pattern on this?

**Comment by suryanaga** [comment] 2017-02-06 14:25
This seems to be a duplicate of #78

**Closed as completed by suryanaga** 2017-02-06 14:25 UTC
