### ISSUE TITLE
users felt they need a professional photo to apply for a pass

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#346] opened 2017-04-13 07:38 UTC

**Comment by suryanaga** [comment] 2017-04-13 09:25
@joanneSouthern Could you give some more information about what you asked users, which page they were on, and what they said? Thanks

**Comment by joanneSouthern** [comment] 2017-04-13 09:39
right at the very beginning, they had low IT skills, weren't confident with the mouse and were use to ipads rather then computers

**Comment by suryanaga** [comment] 2017-04-13 09:42
@joanneSouthern So by right at the beginning, do you mean the [start page](https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/example-service/start-page)?

**Comment by joanneSouthern** [comment] 2017-04-13 09:46
sorry @sanjaypoyzer this one is when the photo guidance appeared and they realised they needed a photo on the computer, 
they all said they would need assistance with the whole process right from the start page in terms of their skill set

**Comment by suryanaga** [comment] 2017-04-13 10:14
@joanneSouthern Ok sure, I think the thing about them needing assistance is a separate issue though. This one's more about them thinking they need a professional photo. I'm just trying to understand what gave them this impression, so we can change it. At the moment, the ["You need a photo" page](https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/example-service/need-photo) doesn't specify anything about the photo being professionally taken, so if that's the page that implies it to them, possibly the best thing to do is to add some text saying it doesn't need to a professional photo.

Although there's already lots to take in on that page so I don't want to add unless we're sure it's necessary to reassure people!

**Comment by joanneSouthern** [comment] 2017-04-13 10:23
@sanjaypoyzer i think its because last time they applied they thats what they did

**Comment by suryanaga** [comment] 2017-04-13 10:53
Ok, I'll add something in then.

**Comment by petegale** [comment] 2017-04-25 13:21
None of the users thought they would have to have a photo professionally taken (CT R2) 
Some were later told that they would need to go to a photo shop and objected to this.
Closing this issue for now.

**Closed as completed by petegale** 2017-04-25 13:21 UTC
Labels: Northumberland, upload-photo, Concessionary Travel

**Comment by suryanaga** [comment] 2017-05-02 09:48
This is a duplicate of #200
