### ISSUE TITLE
user wanting more information about one off payment

### ISSUE THREAD

**Issue by CTSunderland** [alphagov/verify-local-patterns#618] opened 2017-07-04 13:01 UTC
![user wanting more information about one off payment](https://user-images.githubusercontent.com/27339521/27831154-51f5044a-60c1-11e7-8312-dc2496cabdf9.PNG)

**Comment by EUzkuraityte** [comment] 2017-07-05 10:36
closing , as the issue is explored in #597 (evidence copied over)

**Closed as completed by EUzkuraityte** 2017-07-05 10:36 UTC
