### ISSUE TITLE
At the first page of the Verify hub, some users reported confusion about how this related to applying for a bus pass

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#197] opened 2017-02-28 15:46 UTC
Some were further confused by the presence of the identity providers.

Giving users a better understanding of why they are being verified may improve this.

**Comment by petegale** [comment] 2017-03-03 15:10
![screen shot 2017-03-03 at 15 09 46](https://cloud.githubusercontent.com/assets/2970019/23556152/7e042eca-0023-11e7-937a-e35dc6aea50d.png)

**Comment by suryanaga** [comment] 2017-04-20 14:34
Closing this as a duplicate of #190.

**Closed as completed by suryanaga** 2017-04-20 14:34 UTC
Labels: Concessionary Travel, verify-hub-pages
