### ISSUE TITLE
Users wanted to apply for more than one permit during a single application

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#330] opened 2017-04-11 14:10 UTC
![issue9](https://cloud.githubusercontent.com/assets/27288208/24913405/069d235e-1ec9-11e7-88a3-ca8aaa7cfb12.PNG)

**Comment by suryanaga** [comment] 2017-04-11 15:22
This is a duplicate of #224.

**Closed as completed by suryanaga** 2017-04-11 15:22 UTC
Labels: Parking Permits
