### ISSUE TITLE
User choosing one permit are prompted to make a payment.

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#565] opened 2017-06-12 13:42 UTC
![issue 7](https://user-images.githubusercontent.com/27288208/27036618-541db80c-4f7d-11e7-8b83-80b31caed5a2.PNG)

**Comment by EUzkuraityte** [comment] 2017-06-12 14:31
Closing this as duplicate of #537

**Closed as completed by EUzkuraityte** 2017-06-12 14:31 UTC
