### ISSUE TITLE
Front page mentions a passport style photo, which isn't accurate

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#222] opened 2017-03-06 13:18 UTC
We specifically say on this page You’ll upload a passport-style digital photo as part of the application. This isn't accurate, as we can accept photos that aren't passport style

![image](https://cloud.githubusercontent.com/assets/24895693/23611436/48bd75a2-026f-11e7-8b3b-f5a71022039a.png)

**Comment by suryanaga** [comment] 2017-03-14 11:36
It says "passport style" not "passport regulation" - Which I think is a fair description of the type of photo that's needed. Potentially we could reword as "photocard style" but I'm not sure that it's a big issue.

**Comment by ghost** [comment] 2017-03-14 11:44
Given there are so many assumptions about the photo anyway I'm sure there's a lot more we can do further down the journey that'll be much more effective. If bucks still want to try this, could do it as part of the local prototype and see what happens.

**Comment by suryanaga** [comment] 2017-03-20 14:14
Closing this as it's essentially a duplicate of #200.

**Closed as completed by suryanaga** 2017-03-20 14:14 UTC
Labels: content-fix, Start page, Concessionary Travel
