### ISSUE TITLE
Application complete: Users were unclear that they had finished or what the reference number means

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#451] opened 2017-04-24 09:33 UTC
Impact: Users are left feeling unsure they have successfully completed the process.
Evidence: “No payment successful screen.”
“Why do I want a reference number?”
“Payment confirmation – other online service end with this.”
“Want a payment receipt – would rather get this automatically than have to sign up for it.”

**Comment by EUzkuraityte** [comment] 2017-04-25 10:09
Duplicate of #237

**Closed as completed by EUzkuraityte** 2017-04-25 10:09 UTC
Labels: Parking Permits, Oxfordshire
