### ISSUE TITLE
ability to sign up for notifications in multiple channels

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#142] opened 2017-02-13 16:57 UTC
Hi @sanjaypoyzer 
could you change it to allow the user enter multiple means for being contacted, not just one.

https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/add_contact_details

**Comment by suryanaga** [comment] 2017-02-13 17:02
@EUzkuraityte Could you explain more about why the user would need to enter multiple means for contact?

**Comment by EUzkuraityte** [comment] 2017-02-13 17:07
they might prefer to be contacted by email, but in case something is urgent they may allow to be contacted via email. Phone and email combo is pretty standard anyway so probs shouldn't be an issue. Plus from the service point of view, in case one of the contact details are mistyped or invalid they'll always have a back up option.

**Comment by suryanaga** [comment] 2017-02-13 17:33
What urgent messages might the council send about parking permits?

The problem with a backup is that the user will then get the notification twice, which previous research has shown to be something users don't like. This is why our current pattern is radio buttons rather than check boxes. ([Some more info about this pattern here](https://designpatterns.hackpad.com/Notification-preferences-interaction-patterns-LUrQxDycQTZ).)

**Comment by EUzkuraityte** [comment] 2017-02-14 08:52
@sanjaypoyzer the user wouldn't get the message twice. Most councils have email notifications as default method for contact and only use telephone if the emails bounce back (it all comes down to cost in the end...). 

Good link btw, happy to follow their suggestion and ask for one primary contact method but would also like to give the users an opportunity to enter a back up if they wish.

**Comment by suryanaga** [comment] 2017-03-03 09:25
This came up in the Con Travel research but I want to talk to the Notify team a bit more about it.

**Comment by suryanaga** [comment] 2017-03-21 16:16
Duplicate of #186

**Closed as completed by suryanaga** 2017-03-21 16:16 UTC
Labels: Concessionary Travel, Parking Permits, contact-details
