### ISSUE TITLE
User expected cursor to auto-forward (already discussed on previous UR)

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#560] opened 2017-06-12 13:37 UTC
![issue 2](https://user-images.githubusercontent.com/27288208/27036420-aae49062-4f7c-11e7-9168-994167d5f86b.PNG)

**Comment by EUzkuraityte** [comment] 2017-06-12 14:39
Closing as duplicate of #323

**Closed as completed by EUzkuraityte** 2017-06-12 14:39 UTC
