### ISSUE TITLE
Some thought that a webcam or smartphone would not produce an acceptable photo

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#201] opened 2017-02-28 15:49 UTC
Some users incorrectly assumed that passport photo criteria would apply.

These users were less likely to attempt to take a photo themselves and thought that smartphone or webcam pictures would not be accepted. Some reported they would need to go to a photo booth or shop, yet were unsure how they would add that to the form.

When first viewing this page, some users saw the example photo, scanned the criteria and then spoke about how these were the same as for a passport.

**Comment by suryanaga** [comment] 2017-05-02 09:47
Closing this as a duplicate of #200

**Closed as completed by suryanaga** 2017-05-02 09:47 UTC
Labels: upload-photo, Concessionary Travel
